[package]
name = "delivery_contract"
version = "0.2.0"
edition = "2021"
license = "MIT"

[lib]
path = "lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { workspace = true }
shared_types = { path = "../shared_types" }
identity_reputation_contract = { path = "../identity_reputation_contract" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
proptest = "1"
