[package]
name = "fleet_management_contract"
version.workspace = true
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]
path = "lib.rs"

[dependencies]
soroban-sdk = { workspace = true }
shared_types = { path = "../shared_types" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
identity_reputation_contract = { path = "../identity_reputation_contract" }
escrow_contract = { path = "../escrow_contract" }
delivery_contract = { path = "../delivery_contract" }
